Repository walmartlabs/cookie-cutter, pull requests merged in 2020-02, with the labels that each got.

#54 kubernetes: update @kubernetes/client-node package to 0.11.1
  packages/kubernetes/package.json
  yarn.lock
Labels: M-k8s, bug, dependencies

#56 kubernetes: add in additional logging details for watch errors
  packages/kubernetes/package.json
  packages/kubernetes/src/KubernetesWatchSource.ts
Labels: M-k8s

#59 improve timeout of k8s watch
  packages/kubernetes/package.json
  packages/kubernetes/src/KubernetesWatchSource.ts
Labels: M-k8s, bug

#55 Allow opt-in to creating Azure queues dynamically on write
  packages/azure/package.json
  packages/azure/src/__test__/utils/QueueClient.test.ts
  packages/azure/src/streaming/index.ts
  packages/azure/src/streaming/internal/config.ts
  packages/azure/src/utils/QueueClient.ts
Labels: M-azure, enhancement

#60 core: update ConsoleLogger to correctly log out nested objects
  packages/core/package.json
  packages/core/src/__test__/defaults/ConsoleLogger.test.ts
  packages/core/src/defaults/ConsoleLogger.ts
Labels: M-core, bug

#61 kubernetes: create k8sPollSource that periodically polls for resources instead of using a watch
  packages/kubernetes/package.json
  packages/kubernetes/src/KubernetesBaseSource.ts
  packages/kubernetes/src/KubernetesPollSource.ts
  packages/kubernetes/src/KubernetesWatchSource.ts
  packages/kubernetes/src/__test__/KubernetesPollSource.test.ts
  packages/kubernetes/src/index.ts
Labels: M-k8s, enhancement

#65 Add preprocessor concept for Azure Queues to support messages not following the envelope format
  packages/azure/package.json
  packages/azure/src/streaming/index.ts
  packages/azure/src/streaming/internal/QueueInputSource.ts
  packages/azure/src/streaming/internal/config.ts
  packages/azure/src/utils/QueueClient.ts
Labels: M-azure, enhancement

#67 fix lint errors
  packages/azure/src/streaming/internal/QueueInputSource.ts
  packages/azure/src/streaming/internal/config.ts
  packages/azure/src/utils/QueueClient.ts
Labels: bug

#68 refactor queue client to avoid exporting type from azure library as p…
  packages/azure/src/__test__/utils/QueueClient.test.ts
  packages/azure/src/streaming/index.ts
  packages/azure/src/streaming/internal/QueueInputSource.ts
  packages/azure/src/utils/QueueClient.ts
Labels: M-azure, bug

#70 kubernetes: add in timeout to poll request in case request to k8s hangs
  packages/kubernetes/package.json
  packages/kubernetes/src/KubernetesPollSource.ts
Labels: M-k8s

#69 Fix bug when options are ignored in QueueClient
  packages/azure/package.json
  packages/azure/src/__test__/utils/QueueClient.test.ts
  packages/azure/src/streaming/index.ts
  packages/azure/src/utils/QueueClient.ts
  packages/grpc/package.json
Labels: M-azure, bug
