Repository walmartlabs/cookie-cutter, pull requests merged in 2022-01, with the labels that each got.

#309 Add logs to composite input source to debug lost sources
  packages/core/package.json
  packages/core/src/__test__/internal/helpers.test.ts
  packages/core/src/internal/CompositeInputSource.ts
  packages/core/src/internal/helpers.ts
Labels: enhancement, M-core

#310 Bug/fix vulnerabilities
  yarn.lock
Labels: bug, dependencies

#312 Fix vulnerabilities
  yarn.lock
Labels: bug, dependencies

#314 Fix vulnerabilities in master
  yarn.lock
Labels: bug, dependencies

#304 Gcp pubsub
  packages/gcp/package.json
  packages/gcp/src/PubSubSink.ts
  packages/gcp/src/PubSubSource.ts
  packages/gcp/src/__test__/PubSubSink.test.ts
  packages/gcp/src/__test__/PubSubSource.test.ts
  packages/gcp/src/config.ts
  packages/gcp/src/index.ts
  packages/gcp/src/model.ts
Labels: enhancement, M-gcp
